[package]
name = "dorion"
version = "5.0.1"
description = "Tiny alternative Discord client with a smaller footprint, themes and plugins, multi-profile, and more!"
authors = ["SpikeHD"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "debuginfo"
lto = true

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
async-recursion = "1.1.1"
base64 = "0.22.1"
dirs = "5.0.1"
include-flate = "0.3.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.7.2", features = ["macos-private-api", "windows7-compat", "api-all", "icon-ico", "icon-png", "system-tray", "devtools"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1"}
tauri-plugin-deep-link = { version = "^0.1.2" }
reqwest = { version = "0.12.4", features = ["blocking"] }
phf = "0.11.2"
window-shadows = { git = "https://github.com/tauri-apps/window-shadows.git", tag = "window-shadows-v0.2.2" }
sysinfo = "0.30.12"

# launch on startup
auto-launch = "0.5.0"

# rpc server
rsrpc = { git = "https://www.github.com/SpikeHD/rsRPC", tag = "v0.14.0" }
window_titles = { git = "https://github.com/SpikeHD/window_titles", branch = "master" }

# window blur
window-vibrancy = "0.4.3"
chrono = "0.4.38"
device_query = "2.1.0"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
webkit2gtk = "0.18.2"
wgpu = { version = "0.20.0", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
objc-foundation = "0.1.1"
cocoa = "0.25.0"
block = "0.1.6"
embed_plist = "1.2.2"

[target.'cfg(windows)'.dependencies]
webview2-com = "0.19.0"
windows-implement = "0.39.0"

[target.'cfg(windows)'.dependencies.windows]
version = "0.39.0"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Com",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

# Also use lld on macos
[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]
